name: release-please

on:
  push:
    branches:
      - develop
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "@shaunxu/release-please-test"
